run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  
  disable:
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0